### PR TITLE
Add a odd or even checker using while loop

### PR DESCRIPTION
**Pull request by AbbeyIT**
A simple program that checks the number if it's even or odd using a while loop

### CODE REVIEW

**Comment by Abhidongre** [comment]
I am merging your pull request into hacktoberfest 2022 repo. Great work done.

**Comment by AbbeyIT** [comment]
Is the project excluded? I received this instead @Abhidongre 
image

**Comment by AbbeyIT** [comment]
Don't you have any label for this project?

**Comment by Abhidongre** [comment]
I have labelled it hacktoberfest.
It think this kind of repositories are only for beginners first pull request. So like this repo contribution won't count for hacktoberfest. Try to make some meaningful contributions to complete all 4 pull request

**Pull request merged**
