### PR TITLE
Create BinaryTree-BFS.cpp Please Consider it under hacktoberfest-accepted

### PR DESCRIPTION
**Pull request by iamakhileshmishra**

### CODE REVIEW

**Comment by Abhidongre** [comment]
I am merging your pull request. But you have to make some high level contributions also so that your 4 pr are completed for hacktoberfest. Great work done.

**Comment by iamakhileshmishra** [comment]
Sure I will make high level contribution from next PR but sir you have not labeled my recent PR as hacktoberfest-accepted because of which it is not counted in my Hacktoberfest account please look on that

**Comment by Abhidongre** [comment]
I have labeled it but this repository is excluded from hacktoberfest few minutes ago as it is very easy to make this type of contribution.

**Comment by iamakhileshmishra** [comment]
Ok

**Pull request merged**
